data:
  raw_path: "data/raw/census-income.csv"
  clean_path: "data/clean/census-income_clean.csv"


models:

  random_forest:
    type: "RandomForestClassifier"
    params:
      n_estimators: 100
      max_depth: 10

  logistic_regressor:
    type: "LogisticRegression"
    params: {}

